id: compound-engineering-loop
name: Compound Engineering Loop
version: 2
description: "Rigorous plan→execute→review cycle based on Compound Engineering principles. 80% of effort goes to planning and review, 20% in execution. Each cycle compounds: plans inform future plans, reviews catch more issues, patterns get documented. Set ANTFARM_MODE=autonomous for unattended execution (used by lfg/slfg)."

polling:
  model: default
  timeoutSeconds: 1800

cron:
  interval_ms: 60000

context:
  task: "{{task}}"
  repo: "{{repo}}"
  branch: "{{branch}}"
  review_issues: ""
  brainstorm_output: ""
  plan_file: ""
  plan_summary: ""
  implementation_summary: ""
  files_changed: ""
  pr_url: ""
  review_notes: ""
  decision: ""
  learnings: ""
  file_created: ""

agents:
  - id: brainstorm
    name: Brainstorm Agent
    role: analysis
    description: Explores requirements and approaches through collaborative dialogue
    timeoutSeconds: 900
    workspace:
      baseDir: agents/brainstorm
      files:
        AGENTS.md: agents/brainstorm/AGENTS.md

  - id: plan
    name: Plan Agent
    role: analysis
    description: Transforms feature descriptions into detailed implementation plans
    timeoutSeconds: 900
    workspace:
      baseDir: agents/plan
      files:
        AGENTS.md: agents/plan/AGENTS.md

  - id: work
    name: Work Agent
    role: coding
    description: Executes work plans efficiently with task tracking
    timeoutSeconds: 1800
    workspace:
      baseDir: agents/work
      files:
        AGENTS.md: agents/work/AGENTS.md

  - id: review
    name: Review Agent
    role: verification
    description: Multi-agent code review before merging with exhaustive analysis
    timeoutSeconds: 1200
    workspace:
      baseDir: agents/review
      files:
        AGENTS.md: agents/review/AGENTS.md

  - id: compound
    name: Compound Agent
    role: coding
    description: Documents learnings to make future work easier
    timeoutSeconds: 600
    workspace:
      baseDir: agents/compound
      files:
        AGENTS.md: agents/compound/AGENTS.md

steps:
  - id: brainstorm
    agent: brainstorm
    input: |
      You are in brainstorming mode. Your job is to explore WHAT to build through collaborative dialogue.

      TASK:
      {{task}}

      REVIEW_ISSUES (empty on first run):
      {{review_issues}}

      Follow the brainstorming workflow in your AGENTS.md.

      Reply with:
      BRAINSTORM_OUTPUT: summary of explored approaches and key decisions
      STATUS: done
    expects: "STATUS: done"
    max_retries: 2
    on_fail:
      escalate_to: human

  - id: plan
    agent: plan
    input: |
      You are in planning mode. Your job is to transform feature descriptions into detailed implementation plans.

      TASK:
      {{task}}

      BRAINSTORM OUTPUT (if exists):
      {{brainstorm_output}}

      Follow the planning workflow in your AGENTS.md.

      Reply with:
      PLAN_FILE: path to created plan
      PLAN_SUMMARY: summary of the plan
      STATUS: done
    expects: "STATUS: done"
    max_retries: 2
    on_fail:
      escalate_to: human

  - id: work
    agent: work
    input: |
      You are in work mode. Your job is to execute plans efficiently.

      TASK:
      {{task}}

      PLAN FILE:
      {{plan_file}}

      PLAN SUMMARY:
      {{plan_summary}}

      REPOSITORY: {{repo}}
      BRANCH: {{branch}}

      REVIEW_ISSUES (if retrying from review):
      {{review_issues}}

      Follow the execution workflow in your AGENTS.md.
      Read the full plan from the PLAN FILE path above.

      Reply with:
      IMPLEMENTATION_SUMMARY: what was implemented
      FILES_CHANGED: list of files
      PR_URL: link to PR (if created)
      STATUS: done
    expects: "STATUS: done"
    max_retries: 2
    on_fail:
      escalate_to: human

  - id: review
    agent: review
    input: |
      You are in review mode. Your job is to perform exhaustive code review.

      TASK:
      {{task}}

      PLAN FILE:
      {{plan_file}}

      PLAN SUMMARY:
      {{plan_summary}}

      IMPLEMENTATION SUMMARY:
      {{implementation_summary}}

      FILES CHANGED:
      {{files_changed}}

      PR URL:
      {{pr_url}}

      Follow the review workflow in your AGENTS.md.
      Read the full plan from the PLAN FILE path above.

      Always output STATUS: done. Output DECISION (approved, needs_fixes, or rejected).
      Output REVIEW_NOTES and REVIEW_ISSUES per your AGENTS.md output format.
    expects: "STATUS: done"
    # ROUTING INTENT (requires antfarm decision routing — Track B):
    # decision_key: DECISION
    # on_decision:
    #   approved: next_step → compound
    #   needs_fixes: retry_step → work
    #   rejected: retry_step → brainstorm
    # Until Track B ships, pipeline is linear: review always advances to compound.
    max_retries: 3
    on_fail:
      escalate_to: human

  - id: compound
    agent: compound
    input: |
      You are in compound mode. Your job is to document learnings for institutional knowledge.

      TASK:
      {{task}}

      PLAN FILE:
      {{plan_file}}

      PLAN SUMMARY:
      {{plan_summary}}

      IMPLEMENTATION_SUMMARY:
      {{implementation_summary}}

      REVIEW_NOTES:
      {{review_notes}}

      REVIEW_ISSUES:
      {{review_issues}}

      DECISION:
      {{decision}}

      Follow the documentation workflow in your AGENTS.md.
      Read the full plan from the PLAN FILE path above if needed.

      Reply with:
      LEARNINGS: summary of documented patterns
      FILE_CREATED: path to documentation
      STATUS: done
    expects: "STATUS: done"
    max_retries: 2
    on_fail:
      escalate_to: human
